Change dynamic to static link for test
So that it compiles without creating multiple definition errors, as can be seen below on a Windows MinGW GFortran compiler

```
[ 59%] Linking Fortran executable test_integrate.exe
C:/MinGW/mingw64_810_SEH/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(compile_options.o):(.text$_gfortran_set_options+0x0): multiple definition of `_gfortran_set_options'
libbspline-fortran.dll.a(d000125.o):(.text+0x0): first defined here
C:/MinGW/mingw64_810_SEH/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(error.o):(.text$_gfortran_os_error+0x0): multiple definition of `_gfortran_os_error'
libbspline-fortran.dll.a(d000117.o):(.text+0x0): first defined here
C:/MinGW/mingw64_810_SEH/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(main.o):(.text$_gfortran_set_args+0x0): multiple definition of `_gfortran_set_args'
libbspline-fortran.dll.a(d000121.o):(.text+0x0): first defined here
C:/MinGW/mingw64_810_SEH/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(string_intrinsics.o):(.text$_gfortran_concat_string+0x0): multiple definition of `_gfortran_concat_string'
libbspline-fortran.dll.a(d000112.o):(.text+0x0): first defined here
C:/MinGW/mingw64_810_SEH/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(transfer.o):(.text$_gfortran_transfer_integer_write+0x0): multiple definition of `_gfortran_transfer_integer_write'
libbspline-fortran.dll.a(d000160.o):(.text+0x0): first defined here
C:/MinGW/mingw64_810_SEH/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(transfer.o):(.text$_gfortran_transfer_real_write+0x0): multiple definition of `_gfortran_transfer_real_write'
libbspline-fortran.dll.a(d000164.o):(.text+0x0): first defined here
C:/MinGW/mingw64_810_SEH/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(transfer.o):(.text$_gfortran_transfer_character_write+0x0): multiple definition of `_gfortran_transfer_character_write'
libbspline-fortran.dll.a(d000155.o):(.text+0x0): first defined here
C:/MinGW/mingw64_810_SEH/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(transfer.o):(.text$_gfortran_st_write+0x0): multiple definition of `_gfortran_st_write'
libbspline-fortran.dll.a(d000136.o):(.text+0x0): first defined here
C:/MinGW/mingw64_810_SEH/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libgfortran.a(transfer.o):(.text$_gfortran_st_write_done+0x0): multiple definition of `_gfortran_st_write_done'
libbspline-fortran.dll.a(d000137.o):(.text+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
mingw32-make.exe[2]: *** [CMakeFiles\test_integrate.dir\build.make:106: test_integrate.exe] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:190: CMakeFiles/test_integrate.dir/all] Error 2
mingw32-make.exe: *** [Makefile:160: all] Error 2
```